docs/references.md
Adds a link to the the LDK architecture diagram in the References page. Also:
- updates Reference page's formatting (alternative ideas welcome)
- links to the most recent rust-lightning docs rather than a specific version
Partial work towards #15.
=> Add reference to LDK architecture

docs/build_node_rust.md
I think `Box<dyn>` is maybe the simplest to understand for new Rust users. We could also use `Arc<dyn>` or simply `&dyn `.
Addresses the issue noted at https://github.com/lightningdevkit/lightningdevkit.org/discussions/55#discussioncomment-1044139
=> Make filter initialization compile

docs/build_node_rust.md
In Rust, an upcoming change will stop the `BackgroundProcessor`'s thread when the object is dropped. Update the guide to store the `BackgroundProcessor` in a variable otherwise the thread would be stopped immediately after it is started.
=> Update BackgroundProcessor init in Build a Node guide

docs/tutorials/build_a_node_in_java.md
Step 4 initializes a `NetGraphMsgHandler` object.
It seems the goal of the `NetGraphMsgHandler router` is to be used as parameter to `ChannelManagerConstructor` but currently this class takes an `@Nullable NetworkGraph net_graph` as parameter and [internally initializes](https://github.com/lightningdevkit/ldk-garbagecollected/blob/99d1a3bd6dc5c7ed1499b30bfc2b4c66ffaf858a/src/main/java/org/ldk/batteries/ChannelManagerConstructor.java#L101) a `NetGraphMsgHandler` object.
Perhaps the code from step 4 refers to an older implementation.
This PR updates this if that is the case.
=> Update step 4 to use NetworkGraph

docs/tutorials/build_a_node_in_java.md
There appears to be an error in step 6. 
There is [no implicit conversion](https://github.com/lightningdevkit/ldk-garbagecollected/blob/99d1a3bd6dc5c7ed1499b30bfc2b4c66ffaf858a/src/main/java/org/ldk/structs/ChannelManagerPersister.java#L15) between `ChannelManagerConstructor.EventHandler` and `ChannelManagerConstructor.ChannelManagerPersister` as suggested in the last line in this step.
And also `channel_manager_persister` is passed as parameter to `chain_sync_completed` in step 12, but this [method has](
https://github.com/lightningdevkit/ldk-garbagecollected/blob/99d1a3bd6dc5c7ed1499b30bfc2b4c66ffaf858a/src/main/java/org/ldk/batteries/ChannelManagerConstructor.java#L179) `EventHandler event_handler` as parameter and not `ChannelManagerConstructor.ChannelManagerPersister`.
=> Update step 6 to use EventHandler

docs/.vuepress/config.js, docs/.vuepress/styles/palette.styl, docs/blockchain_data/block_source.md, docs/blockchain_data/pre_filtered_blocks.md, docs/payments/connecting_peers.md, docs/payments/managing_channels.md, docs/payments/receiving_payments.md, docs/payments/sending_payments.md, docs/tutorials/build_a_node_in_java.md, docs/tutorials/build_a_node_in_rust.md, package-lock.json, package.json
* Center images
* [Use code switcher instead of tabs](https://github.com/lightningdevkit/lightningdevkit.org/commit/75879be43a21560944790fa159fd73ec87243bcc) (as discussed in #133)
=> Upgrade theme

docs/.vuepress/config.js, docs/tutorials/getting-started.md
[Preview](https://deploy-preview-133--lightningdevkit.netlify.app/tutorials/getting-started/)
=> Adds getting started installation instructions

docs/tutorials/build_a_node_in_rust.md
Got a 404 when following the blockchain data guide link in the [Rust tutorial](https://lightningdevkit.org/tutorials/build_a_node_in_rust/). 
This PR should fix it.
=> Fix `blockchain_data` guide link

docs/blockchain_data/confirmed_transactions.md
Hope this clarifies this section a bit.
=> Improve 'Confirmed Transactions' section

docs/blockchain_data/pre_filtered_blocks.md
This reflects the changes made to the `Filter::register_output` interface in [rust-lightning#1663](https://github.com/lightningdevkit/rust-lightning/pull/1663). 
Should hence only get merged after/if this lands.
=> Reflect removed return value of `register_output`

docs/tutorials/build_a_node_in_java.md, docs/tutorials/build_a_node_in_rust.md
A lot of the newer(?) event types were missing from the `EventHandler` sections of the tutorials. I think it makes sense to list them all so that the user can get an understanding of what potentially needs to be handled. 
Let me however know if they had been omitted intentionally for the sake of brevity.
=> Update list of `Event`s to handle in tutorials.

docs/key_management.md
This PR adds guidance on how to allow for a single wallet setup using a BIP32 HD wallet + Hardened Child Key when seeding LDK. 
Minor TODO:
- Add Java sample code 
[Preview](https://deploy-preview-175--lightningdevkit.netlify.app/key_management/#creating-a-unified-wallet)
=> Adds combined wallet guidance

docs/blockchain_data/confirmed_transactions.md
=> Mention ordering requirements

docs/tutorials/build_a_node_in_rust.md
As it been moved to `PeerManager` since ~0.0.110.
=> Fix docs for moved `broadcast_node_announcement`

docs/_blog/onion-messages-demystified.md
We don't want to assume that async payment channel counterparties are necessarily LSPs. 
cc @moneyball
=> Update OM blog for latest async payments parlance

docs/key_management.md
This introduces a basic Rust example on how to wrap `KeysManager` in order to make outputs spendable by a BDK wallet. 
Probably not complete as it needs to be complemented with Java/Kotlin counterparts.
=> Add BDK-based `KeysManager` example

docs/key_management.md, docs/overview/private_key_management.md, docs/tutorials/build_a_node_in_java.md, docs/tutorials/build_a_node_in_rust.md
moved in this PR: https://github.com/lightningdevkit/rust-lightning/pull/2246
=> Update KeysManager link

docs/building-a-node-with-ldk/handling-events.md, docs/introduction/index.md
As shown in [this issue](https://github.com/lightningdevkit/lightningdevkit.org/issues/260), the `architecture` link is broken in two places:
- `introduction/`
- `building-a-node-with-ldk/handling-events/`
=> links: fix architecture broken link.

docs/_blog/bolt12-has-arrived.md
The BOLT12 blog post was based on a beta release of LDK 0.0.123. Update it to account for changes made for the final release.
=> Update BOLT12 blog for final 0.0.123 release

docs/.vuepress/config.js, docs/fee_estimation.md
This PR is a first-draft submission for ```FeeEstimator``` documentation (including best practices). Once complete, it will close #153.
As of now, I submitted the documentation as a single file, since this will make it easier for others to read and provide comments. However, once the final edits are made, I think it would look best if I made it collapsable - like how the [Blockchain Data section](https://lightningdevkit.org/blockchain_data/introduction/) on the LDK Docs website has multiple sub-sections (ex: Introduction, Chain Activity, etc.). If this documentation followed that model, it would have the following sub-sections:
- Overview
- Fee Estimator
- Confirmation Target
- Best Practices
- Code Example
Once we finalize the edits and align on the right format, I will update the PR to …
=> Add Fee Estimation Documentation & Best Practices

docs/fee_estimation.md
This PR updates the Fee Estimation docs, incorporating the new ```ConfirmationTarget```s outlined in this [PR](https://github.com/lightningdevkit/rust-lightning/pull/3268).
Changes are the following:
1.  Updated the ConfirmationTarget table with new Confirmation Targets (```MaximumFeeEstimate```, ```UrgentOnChainSweep```)
2. Added commentary to **Best Practices** and **Off-Chain** sections regarding how to understand and populate ```MaximumFeeEstimate```.
=> Update Fee Estimation Docs

docs/key_management.md
The above comment explains that the timestampSeconds and timestampNanos variables are used to capture the current system time, which is then utilized to ensure uniqueness across multiple instances or restarts of the application.
=> Appropriate comment to explain timestampSeconds and timestampNanos variables

docs/.vuepress/public/llms.txt
Adds support for [LLMs.txt](https://llmstxt.org/) files for making the LDK documentation available to large language models.
=> Adds LLMs text file
