- docs/build_node.md
> Revamp Build a Node guide

- docs/blockdata.md
- docs/build_node.md
- docs/key_mgmt.md
- docs/overview.md
Our Java code samples were quite out of date. This updates them.
Next up: complete the "Using LDK" code samples and add a Rust-specific guide.
Supercedes #36
> Update Build a Node Java guide

- docs/build_node.md
- docs/build_node_rust.md
- docs/overview.md
- sidebars.js
> Add Build a Node Rust Guide

- docs/build_node.md
Jeff noted that the invoice parsing sample was bogus. This fixes it.
> Fix Java invoice parsing sample

- docs/.vuepress/config.js
- docs/.vuepress/styles/index.styl
- docs/.vuepress/theme/components/Footer.vue
> Vuepress: Integrate footer

- docs/.vuepress/theme/components/Home.vue
- docs/index.md
Content not finished, but editable in `index.md`. Closes #62.
> Vuepress: Add features to homepage

- docs/blockdata.md
> Add chain::Confirm use to Blockchain Data guide

- docs/basic-features/receiving_payments.md
> Fix typo in receiving_payments.md

- docs/tutorials/build_a_node_in_rust.md
Also reorders steps to match the LDK sample node...
> Adds ProbabilisticScorer and InvoicePayer examples

- docs/_blog/ldk-an-sdk-for-the-lightning-network.md
Fixes https://github.com/lightningdevkit/lightningdevkit.org/issues/128 & https://github.com/lightningdevkit/lightningdevkit.org/issues/129
> Blog update

- package-lock.json
- package.json
In #137 I made a mistake which leads to the indentation of the nav as well, this commit fixes that.
> Upgrade theme

- docs/.vuepress/config.js
Closes - https://github.com/lightningdevkit/lightningdevkit.org/issues/162
Adds link in the footer for now. Probably deserves its own section on the landing page in the near future. 
[Preview](https://deploy-preview-165--lightningdevkit.netlify.app/)
> Adds link to LDK review club website

- docs/_blog/cashapp-enables-lightning-withdrawals-and-deposits-using-ldk.md
[Preview](https://deploy-preview-176--lightningdevkit.netlify.app/blog/cashapp-enables-lightning-withdrawals-and-deposits-using-ldk/)
> Minor edits to Cash App case study

- docs/index.md
I've seen the term unified wallet more recently, and it seems to be more descriptive. If others agree, let's change the LDK home page.
> Rename "Single Wallet" to "Unified Wallet"

- docs/.vuepress/config.js
Closes - https://github.com/lightningdevkit/lightningdevkit.org/issues/151
> Adds LDK Google Calendar link to footer

- docs/.vuepress/config.js
Closes https://github.com/lightningdevkit/lightningdevkit.org/issues/190
> Add API reference link for RGS

- docs/.vuepress/config.js
[Preview](https://deploy-preview-212--lightningdevkit.netlify.app/introduction/)
> Updates API reference links

- docs/examples.md
[Preview](https://deploy-preview-236--lightningdevkit.netlify.app/examples/)
> Adds new samples to examples page

- docs/case-studies.md
> Remove lipa from case studies 

- docs/.vuepress/config.js
> link to lightning_custom_message crate

- docs/_blog/unleashing-liquidity-on-the-lightning-network-with-lightning-liquidity.md
Preview - https://deploy-preview-254--lightningdevkit.netlify.app/blog/unleashing-liquidity-on-the-lightning-network-with-lightning-liquidity/
> Adds lightning liquidity blog post

- docs/_blog/unleashing-liquidity-on-the-lightning-network-with-lightning-liquidity.md
Reverts lightningdevkit/lightningdevkit.org#255
> Revert "Revert "Adds lightning liquidity blog post""

- docs/.vuepress/config.js
Copying bitcoindevkit.org's idea from:
https://github.com/bitcoindevkit/bitcoindevkit.org/blob/master/docs/.vuepress/config.js#L164
> Use getUTCFullYear() to get current year.
